# Generated by Django 4.2.10 on 2026-02-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='code',
            field=models.CharField(default='TEMP', help_text='Unique code for institution login/registration', max_length=20, unique=True),
        ),
    ]
