import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from core.models import Lesson, Quiz, Question

def create_content():
    # 1. Lesson: Introduction to Sustainability
    lesson1, created = Lesson.objects.get_or_create(
        title="Introduction to Sustainability",
        defaults={
            "content": "# What is Sustainability?\n\nSustainability means meeting our own needs without compromising the ability of future generations to meet their own needs.\n\n## The Three Pillars\n1. Environmental\n2. Social\n3. Economic",
            "points_reward": 10,
            "order": 1
        }
    )
    if created:
        print(f"Created Lesson: {lesson1.title}")
    else:
        print(f"Lesson already exists: {lesson1.title}")

    # Quiz for Lesson 1
    quiz1, created = Quiz.objects.get_or_create(
        lesson=lesson1,
        defaults={
            "title": "Sustainability Basics Quiz",
            "description": "Test your knowledge on the three pillars of sustainability.",
            "points_reward": 20
        }
    )
    
    if created:
        print(f"Created Quiz: {quiz1.title}")
        # Questions
        Question.objects.create(
            quiz=quiz1,
            text="Which of the following is NOT one of the three pillars of sustainability?",
            options=["Environmental", "Social", "Technological", "Economic"],
            correct_option_index=2
        )
        Question.objects.create(
            quiz=quiz1,
            text="What is the main goal of sustainability?",
            options=["To make as much money as possible", "To consume all resources", "To balance needs of present and future", "To stop all development"],
            correct_option_index=2
        )
        print("Added questions to Quiz 1")

    # 2. Lesson: Reducing Carbon Footprint
    lesson2, created = Lesson.objects.get_or_create(
        title="Reducing Carbon Footprint",
        defaults={
            "content": "# Reducing Your Carbon Footprint\n\nCarbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.\n\n## Tips\n- Walk or bike more\n- Eat less meat\n- Unplug electronics",
            "points_reward": 15,
            "order": 2
        }
    )
    if created:
        print(f"Created Lesson: {lesson2.title}")

if __name__ == "__main__":
    create_content()
