# Generated by Django 4.2.10 on 2026-02-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lesson_options_lesson_order_lesson_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecotask',
            name='image_url',
        ),
        migrations.AddField(
            model_name='ecotask',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/'),
        ),
    ]
